### ISSUE TITLE
Translate the code from C# to C++

### ISSUE THREAD

**Issue by Konard** [linksplatform/Timestamps#32]
400 RUB reward can be claimed by anyone who completes this task.

**Comment by uselessgoddess** [comment]
What do you propose replace ```System.DateTime```?

**Comment by Konard** [comment]
> What do you propose replace `System.DateTime`?

Looks like we should use something like `std::chrono::high_resolution_clock` with `std::chrono::nanoseconds` precision. It is not directly compatible with `System.DateTime`. `System.DateTime` uses 100-nanoseconds ticks, and uses 12:00 midnight, January 1, 0001 A.D. (C.E.) in the GregorianCalendar calendar as an epoch.

> The DateTime value type represents dates and times with values ranging from 00:00:00 (midnight), January 1, 0001 Anno Domini (Common Era) through 11:59:59 P.M., December 31, 9999 A.D. (C.E.) in the Gregorian calendar.
https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=net-5.0

Though it is possible to create 100% compatible custom clock (https://stackoverflow.com/questions/16533156/how-to-create-a-custom-clock-for-use-in-stdchrono-functions), I think we can just use the default clock, but with `std::chrono::nanoseconds` precision.

What do you think?

**Comment by uselessgoddess** [comment]
I was thinking about `std::chrono`, but it is really incompatible with `System.DateTime` because it has a different purpose. We can try to make a compatible custom analog.

**Comment by Konard** [comment]
Why do think there is a difference in purpose?

We can use 
https://stackoverflow.com/questions/39459474/convert-c-sharp-datetime-to-c-stdchronosystem-clocktime-point
and 
https://stackoverflow.com/questions/16533156/how-to-create-a-custom-clock-for-use-in-stdchrono-functions

To create `CommonEraClock`, to make `std::chrono` work fine and be compatible with `System.DateTime`.

**Comment by uselessgoddess** [comment]
Ok. C++20 standart add many new calendar features 
https://en.cppreference.com/w/cpp/chrono

**Comment by Konard** [comment]
> Ok. C++20 standart add many new calendar features
> https://en.cppreference.com/w/cpp/chrono

Yes.

**Comment by uselessgoddess** [comment]
`utc_clock`
`tai_clock` 
`gps_clock`
does not supported))
https://godbolt.org/z/5os8dKse1

**Comment by norwend** [comment]
> `utc_clock`
> `tai_clock`
> `gps_clock`
> does not supported))
> https://godbolt.org/z/5os8dKse1

No, they are supported, you need to set the -std=c++20 parameter in order for these types to work. But utc_clock::now() still doesn't work, trying to figure out why

**Comment by uselessgoddess** [comment]
It's time for update glib

**Comment by Konard** [comment]
@norwend claimed the reward of 400 RUB.
